### ISSUE TITLE
Something missed in the script "oneclass_sarscov2.py"

### ISSUE THREAD

**Issue by sweety919** [GiovannaNicora/predicting_sarscov2_variants#1]
![1676423931(1)](https://user-images.githubusercontent.com/113670467/218900413-2e49b97a-a95d-477c-a6a0-85df17a96049.png)
The script references functions from two custom scripts, but they are not shown in your project. Is it convenient for you to upload them on Github?
What's more, could you please provide a reference format for your data set so that readers can use it as a reference when reading the code?

**Comment by GiovannaNicora** [comment]
I have added the missing functions and some examples on how the data should be structured
